"""add status to document

Revision ID: 5339dabc08ce
Revises: 8af3fb44ff97
Create Date: 2026-06-25 21:02:35.015723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5339dabc08ce'
down_revision: Union[str, Sequence[str], None] = '8af3fb44ff97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(), nullable=False, server_default='indexed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
